name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
        bundler: '2.6.8'  # Specify the bundler version
    - name: Configure bundler
      run: bundle config set --local frozen false
    - name: Build the site
      run: bundle exec jekyll build --future
